version: "2"
linters:
  enable:
    - containedctx
    - contextcheck
    - dupl
    - durationcheck
    - errorlint
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - makezero
    - misspell
    - mnd
    - nilerr
    - predeclared
    - revive
    - unconvert
    - unparam
    - wrapcheck
  settings:
    gocyclo:
      min-complexity: 12
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
          severity: warning
          disabled: false
    wrapcheck:
      ignore-sig-regexps:
        - .*github.com/yogeshlonkar/go-grpc-hmac/.*
      ignore-package-globs:
        - github.com/yogeshlonkar/go-grpc-hmac/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - dot
        - prefix(github.com/yogeshlonkar/go-grpc-hmac)
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/yogeshlonkar/go-grpc-hmac
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
