name: Continuous Integration
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - id: setup-go
        name: Setup GO
        uses: actions/setup-go@v6
        with:
          go-version: ^1
      - name: Download dependencies
        if: steps.setup-go.outputs.cache-hit != 'true'
        shell: bash
        run: go get -t ./...
      - name: Go fmt
        run: test -z $(gofmt -l .)
        shell: bash
      - name: Go fmt-diff
        if: failure()
        run: gofmt -e -d .
        shell: bash
      - name: Go vet
        if: success() || failure() # runs everytime except the job is cancelled
        run: go vet ./...
        shell: bash
      - name: Golangci lint
        uses: golangci/golangci-lint-action@v7
        if: success() || failure() # runs everytime except the job is cancelled
        with:
          args: --timeout=1m
      - name: Unit test
        run: go test ./...
      - name: Example
        run: |
          cd example
          go get -t ./...
          ./run.sh
